<%@ page language="java" contentType="text/html; charset=EUC-KR"
    pageEncoding="EUC-KR"%>
<!DOCTYPE html>
<html lang="en">
    <!-- 브라우저 최상단 탭 명 -->
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>관리자페이지</title>
        <link href="../resources/css/admin/styles.css" rel="stylesheet" type="text/css"/> <!-- css파일 import -->
        <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
    </head>

    <!-- 페이지 내용 부분 -->
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- 상단 제목 -->
            <a class="navbar-brand" href="../admin.jsp">관리자 페이지</a>
            <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"></button>
            <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            </form>
            <!-- 회원 아이콘 드롭다운 메뉴 -->
            <ul class="navbar-nav ml-auto ml-md-0"> 
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user fa-fw"></i></a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    
                    <!-- 메인페이지 이동 -->
                        <a class="dropdown-item" href="../all/homepage.do">메인 페이지 이동</a> 
                        <div class="dropdown-divider"></div>
                    <!-- 메인화면 로그인창으로 이동 -->
                    <a class="dropdown-item" href="#">로그 아웃</a>
                    </div>
                </li>
            </ul>
        </nav>
        
        <!-- 좌측 메뉴 -->
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading"><h4>메뉴</h4></div>  
                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>회원관리
                            </a>
                            <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion" style="">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="./userlist.do">회원목록</a>
                                    <a class="nav-link" href="./withdrawal.do">탈퇴회원목록</a> 
                                    <a class="nav-link" href="./blacklist.do">블랙리스트목록</a>
                                    <a class="nav-link" href="./createAdmin.do">관리자생성</a>
                                    <a class="nav-link" href="./adminlist.do">관리자목록</a>  
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseone" aria-expanded="false" aria-controls="collapseAdd">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>코인현황
                            </a>
                            <div class="collapse" id="collapseone" aria-labelledby="headingOne" data-parent="#sidenavAccordion" style="">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="./dailycoin.do">일별코인충전</a>
                                    <a class="nav-link" href="./monthlycoin.do">월별코인충전</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsetwo" aria-expanded="false" aria-controls="collapseAdd">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>방문현황
                            </a>
                            <div class="collapse" id="collapsetwo" aria-labelledby="headingOne" data-parent="#sidenavAccordion" style="">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="./dailysales.do">일일방문현황</a>
                                    <a class="nav-link" href="./monthlysales.do">월별방문충전</a>
                                </nav>
                            </div>
                            
                             <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsethree" aria-expanded="false" aria-controls="collapseAdd">
                             <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>게시글관리
                             </a>
                             <div class="collapse" id="collapsethree" aria-labelledby="headingOne" data-parent="#sidenavAccordion" style="">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="./salesarticlelist.do">판매글</a>
                                    <a class="nav-link" href="./userinquiry.do">고객문의</a> 
                                    <a class="nav-link" href="./carnews.do">자동차뉴스</a>
                                    <a class="nav-link" href="./purchasereview.do">구매후기</a>
                                </nav>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
            
            <!-- 대시보드 내용 -->
            <div id="layoutSidenav_content">
                    <div class="container-fluid">
                        <h2 class="mt-4">일별 코인 충전 현황</h2>
                        <div class="card mb-4">
                            <div class="card-header">
                                <i class="fas fa-table mr-1"></i>
                                충전 현황
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    
                                        <!-- 예시 데이터 삽입 -->
                                        <thead>
                                            <tr>
                                                <th>날짜</th>
                                                <th>충전량</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
											   <td>2021/1/1</td>
											   <td>500</td>
											</tr>
											<tr>
											   <td>2021/1/2</td>
											   <td>1000</td>
											</tr>
											<tr>
											   <td>2021/1/3</td>
											   <td>1500</td>
											</tr>
											<tr>
											   <td>2021/1/4</td>
											   <td>2000</td>
											</tr>
											<tr>
											   <td>2021/1/5</td>
											   <td>2500</td>
											</tr>
											<tr>
											   <td>2021/1/6</td>
											   <td>3000</td>
											</tr>
											<tr>
											   <td>2021/1/7</td>
											   <td>3500</td>
											</tr>
											<tr>
											   <td>2021/1/8</td>
											   <td>4000</td>
											</tr>
											<tr>
											   <td>2021/1/9</td>
											   <td>4500</td>
											</tr>
											<tr>
											   <td>2021/1/10</td>
											   <td>5000</td>
											</tr>
											<tr>
											   <td>2021/1/11</td>
											   <td>5500</td>
											</tr>
											<tr>
											   <td>2021/1/12</td>
											   <td>6000</td>
											</tr>
											<tr>
											   <td>2021/1/13</td>
											   <td>6500</td>
											</tr>
											<tr>
											   <td>2021/1/14</td>
											   <td>7000</td>
											</tr>
											<tr>
											   <td>2021/1/15</td>
											   <td>7500</td>
											</tr>
											<tr>
											   <td>2021/1/16</td>
											   <td>8000</td>
											</tr>
											<tr>
											   <td>2021/1/17</td>
											   <td>8500</td>
											</tr>
											<tr>
											   <td>2021/1/18</td>
											   <td>9000</td>
											</tr>
											<tr>
											   <td>2021/1/19</td>
											   <td>9500</td>
											</tr>
											<tr>
											   <td>2021/1/20</td>
											   <td>10000</td>
											</tr>
											<tr>
											   <td>2021/1/21</td>
											   <td>10500</td>
											</tr>
											<tr>
											   <td>2021/1/22</td>
											   <td>11000</td>
											</tr>
											<tr>
											   <td>2021/1/23</td>
											   <td>11500</td>
											</tr>
											<tr>
											   <td>2021/1/24</td>
											   <td>12000</td>
											</tr>
											<tr>
											   <td>2021/1/25</td>
											   <td>12500</td>
											</tr>
											<tr>
											   <td>2021/1/26</td>
											   <td>13000</td>
											</tr>
											<tr>
											   <td>2021/1/27</td>
											   <td>13500</td>
											</tr>
											<tr>
											   <td>2021/1/28</td>
											   <td>14000</td>
											</tr>
											<tr>
											   <td>2021/1/29</td>
											   <td>14500</td>
											</tr>
											<tr>
											   <td>2021/1/30</td>
											   <td>15000</td>
											</tr>
											<tr>
											   <td>2021/1/31</td>
											   <td>15500</td>
											</tr>
											<tr>
											   <td>2021/2/1</td>
											   <td>500</td>
											</tr>
											<tr>
											   <td>2021/2/2</td>
											   <td>1000</td>
											</tr>
											<tr>
											   <td>2021/2/3</td>
											   <td>1500</td>
											</tr>
											<tr>
											   <td>2021/2/4</td>
											   <td>2000</td>
											</tr>
											<tr>
											   <td>2021/2/5</td>
											   <td>2500</td>
											</tr>
											<tr>
											   <td>2021/2/6</td>
											   <td>3000</td>
											</tr>
											<tr>
											   <td>2021/2/7</td>
											   <td>3500</td>
											</tr>
											<tr>
											   <td>2021/2/8</td>
											   <td>4000</td>
											</tr>
											<tr>
											   <td>2021/2/9</td>
											   <td>4500</td>
											</tr>
											<tr>
											   <td>2021/2/10</td>
											   <td>5000</td>
											</tr>
											<tr>
											   <td>2021/2/11</td>
											   <td>5500</td>
											</tr>
											<tr>
											   <td>2021/2/12</td>
											   <td>6000</td>
											</tr>
											<tr>
											   <td>2021/2/13</td>
											   <td>6500</td>
											</tr>
											<tr>
											   <td>2021/2/14</td>
											   <td>7000</td>
											</tr>
											<tr>
											   <td>2021/2/15</td>
											   <td>7500</td>
											</tr>
											<tr>
											   <td>2021/2/16</td>
											   <td>8000</td>
											</tr>
											<tr>
											   <td>2021/2/17</td>
											   <td>8500</td>
											</tr>
											<tr>
											   <td>2021/2/18</td>
											   <td>9000</td>
											</tr>
											<tr>
											   <td>2021/2/19</td>
											   <td>9500</td>
											</tr>
											<tr>
											   <td>2021/2/20</td>
											   <td>10000</td>
											</tr>
											<tr>
											   <td>2021/2/21</td>
											   <td>10500</td>
											</tr>
											<tr>
											   <td>2021/2/22</td>
											   <td>11000</td>
											</tr>
											<tr>
											   <td>2021/2/23</td>
											   <td>11500</td>
											</tr>
											<tr>
											   <td>2021/2/24</td>
											   <td>12000</td>
											</tr>
											<tr>
											   <td>2021/2/25</td>
											   <td>12500</td>
											</tr>
											<tr>
											   <td>2021/2/26</td>
											   <td>13000</td>
											</tr>
											<tr>
											   <td>2021/2/27</td>
											   <td>13500</td>
											</tr>
											<tr>
											   <td>2021/2/28</td>
											   <td>14000</td>
											</tr>
											<tr>
											   <td> </td>
											   <td> </td>
											</tr>
											<tr>
											   <td> </td>
											   <td> </td>
											</tr>
											<tr>
											   <td> </td>
											   <td> </td>
											</tr>
											<tr>
											   <td>2021/3/1</td>
											   <td>500</td>
											</tr>
											<tr>
											   <td>2021/3/2</td>
											   <td>1000</td>
											</tr>
											<tr>
											   <td>2021/3/3</td>
											   <td>1500</td>
											</tr>
											<tr>
											   <td>2021/3/4</td>
											   <td>2000</td>
											</tr>
											<tr>
											   <td>2021/3/5</td>
											   <td>2500</td>
											</tr>
											<tr>
											   <td>2021/3/6</td>
											   <td>3000</td>
											</tr>
											<tr>
											   <td>2021/3/7</td>
											   <td>3500</td>
											</tr>
											<tr>
											   <td>2021/3/8</td>
											   <td>4000</td>
											</tr>
											<tr>
											   <td>2021/3/9</td>
											   <td>4500</td>
											</tr>
											<tr>
											   <td>2021/3/10</td>
											   <td>5000</td>
											</tr>
											<tr>
											   <td>2021/3/11</td>
											   <td>5500</td>
											</tr>
											<tr>
											   <td>2021/3/12</td>
											   <td>6000</td>
											</tr>
											<tr>
											   <td>2021/3/13</td>
											   <td>6500</td>
											</tr>
											<tr>
											   <td>2021/3/14</td>
											   <td>7000</td>
											</tr>
											<tr>
											   <td>2021/3/15</td>
											   <td>7500</td>
											</tr>
											<tr>
											   <td>2021/3/16</td>
											   <td>8000</td>
											</tr>
											<tr>
											   <td>2021/3/17</td>
											   <td>8500</td>
											</tr>
											<tr>
											   <td>2021/3/18</td>
											   <td>9000</td>
											</tr>
											<tr>
											   <td>2021/3/19</td>
											   <td>9500</td>
											</tr>
											<tr>
											   <td>2021/3/20</td>
											   <td>10000</td>
											</tr>
											<tr>
											   <td>2021/3/21</td>
											   <td>10500</td>
											</tr>
											<tr>
											   <td>2021/3/22</td>
											   <td>11000</td>
											</tr>
											<tr>
											   <td>2021/3/23</td>
											   <td>11500</td>
											</tr>
											<tr>
											   <td>2021/3/24</td>
											   <td>12000</td>
											</tr>
											<tr>
											   <td>2021/3/25</td>
											   <td>12500</td>
											</tr>
											<tr>
											   <td>2021/3/26</td>
											   <td>13000</td>
											</tr>
											<tr>
											   <td>2021/3/27</td>
											   <td>13500</td>
											</tr>
											<tr>
											   <td>2021/3/28</td>
											   <td>14000</td>
											</tr>
											<tr>
											   <td>2021/3/29</td>
											   <td>14500</td>
											</tr>
											<tr>
											   <td>2021/3/30</td>
											   <td>15000</td>
											</tr>
											<tr>
											   <td>2021/3/31</td>
											   <td>15500</td>
											</tr>
											<tr>
											   <td>2021/4/1</td>
											   <td>500</td>
											</tr>
											<tr>
											   <td>2021/4/2</td>
											   <td>1000</td>
											</tr>
											<tr>
											   <td>2021/4/3</td>
											   <td>1500</td>
											</tr>
											<tr>
											   <td>2021/4/4</td>
											   <td>2000</td>
											</tr>
											<tr>
											   <td>2021/4/5</td>
											   <td>2500</td>
											</tr>
											<tr>
											   <td>2021/4/6</td>
											   <td>3000</td>
											</tr>
											<tr>
											   <td>2021/4/7</td>
											   <td>3500</td>
											</tr>
											<tr>
											   <td>2021/4/8</td>
											   <td>4000</td>
											</tr>
											<tr>
											   <td>2021/4/9</td>
											   <td>4500</td>
											</tr>
											<tr>
											   <td>2021/4/10</td>
											   <td>5000</td>
											</tr>
											<tr>
											   <td>2021/4/11</td>
											   <td>5500</td>
											</tr>
											<tr>
											   <td>2021/4/12</td>
											   <td>6000</td>
											</tr>
											<tr>
											   <td>2021/4/13</td>
											   <td>6500</td>
											</tr>
											<tr>
											   <td>2021/4/14</td>
											   <td>7000</td>
											</tr>
											<tr>
											   <td>2021/4/15</td>
											   <td>7500</td>
											</tr>
											<tr>
											   <td>2021/4/16</td>
											   <td>8000</td>
											</tr>
											<tr>
											   <td>2021/4/17</td>
											   <td>8500</td>
											</tr>
											<tr>
											   <td>2021/4/18</td>
											   <td>9000</td>
											</tr>
											<tr>
											   <td>2021/4/19</td>
											   <td>9500</td>
											</tr>
											<tr>
											   <td>2021/4/20</td>
											   <td>10000</td>
											</tr>
											<tr>
											   <td>2021/4/21</td>
											   <td>10500</td>
											</tr>
											<tr>
											   <td>2021/4/22</td>
											   <td>11000</td>
											</tr>
											<tr>
											   <td>2021/4/23</td>
											   <td>11500</td>
											</tr>
											<tr>
											   <td>2021/4/24</td>
											   <td>12000</td>
											</tr>
											<tr>
											   <td>2021/4/25</td>
											   <td>12500</td>
											</tr>
											<tr>
											   <td>2021/4/26</td>
											   <td>13000</td>
											</tr>
											<tr>
											   <td>2021/4/27</td>
											   <td>13500</td>
											</tr>
											<tr>
											   <td>2021/4/28</td>
											   <td>14000</td>
											</tr>
											<tr>
											   <td>2021/4/29</td>
											   <td>14500</td>
											</tr>
											<tr>
											   <td>2021/4/30</td>
											   <td>15000</td>
											</tr>
											<tr>
											   <td> </td>
											   <td> </td>
											</tr>
											<tr>
											   <td>2021/5/1</td>
											   <td>500</td>
											</tr>
											<tr>
											   <td>2021/5/2</td>
											   <td>1000</td>
											</tr>
											<tr>
											   <td>2021/5/3</td>
											   <td>1500</td>
											</tr>
											<tr>
											   <td>2021/5/4</td>
											   <td>2000</td>
											</tr>
											<tr>
											   <td>2021/5/5</td>
											   <td>2500</td>
											</tr>
											<tr>
											   <td>2021/5/6</td>
											   <td>3000</td>
											</tr>
											<tr>
											   <td>2021/5/7</td>
											   <td>3500</td>
											</tr>
											<tr>
											   <td>2021/5/8</td>
											   <td>4000</td>
											</tr>
											<tr>
											   <td>2021/5/9</td>
											   <td>4500</td>
											</tr>
											<tr>
											   <td>2021/5/10</td>
											   <td>5000</td>
											</tr>
											<tr>
											   <td>2021/5/11</td>
											   <td>5500</td>
											</tr>
											<tr>
											   <td>2021/5/12</td>
											   <td>6000</td>
											</tr>
											<tr>
											   <td>2021/5/13</td>
											   <td>6500</td>
											</tr>
											<tr>
											   <td>2021/5/14</td>
											   <td>7000</td>
											</tr>
											<tr>
											   <td>2021/5/15</td>
											   <td>7500</td>
											</tr>
											<tr>
											   <td>2021/5/16</td>
											   <td>8000</td>
											</tr>
											<tr>
											   <td>2021/5/17</td>
											   <td>8500</td>
											</tr>
											<tr>
											   <td>2021/5/18</td>
											   <td>9000</td>
											</tr>
											<tr>
											   <td>2021/5/19</td>
											   <td>9500</td>
											</tr>
											<tr>
											   <td>2021/5/20</td>
											   <td>10000</td>
											</tr>
											<tr>
											   <td>2021/5/21</td>
											   <td>10500</td>
											</tr>
											<tr>
											   <td>2021/5/22</td>
											   <td>11000</td>
											</tr>
											<tr>
											   <td>2021/5/23</td>
											   <td>11500</td>
											</tr>
											<tr>
											   <td>2021/5/24</td>
											   <td>12000</td>
											</tr>
											<tr>
											   <td>2021/5/25</td>
											   <td>12500</td>
											</tr>
											<tr>
											   <td>2021/5/26</td>
											   <td>13000</td>
											</tr>
											<tr>
											   <td>2021/5/27</td>
											   <td>13500</td>
											</tr>
											<tr>
											   <td>2021/5/28</td>
											   <td>14000</td>
											</tr>
											<tr>
											   <td>2021/5/29</td>
											   <td>14500</td>
											</tr>
											<tr>
											   <td>2021/5/30</td>
											   <td>15000</td>
											</tr>
											<tr>
											   <td>2021/5/31</td>
											   <td>15500</td>
											</tr>
											<tr>
											   <td>2021/6/1</td>
											   <td>500</td>
											</tr>
											<tr>
											   <td>2021/6/2</td>
											   <td>1000</td>
											</tr>
											<tr>
											   <td>2021/6/3</td>
											   <td>1500</td>
											</tr>
											<tr>
											   <td>2021/6/4</td>
											   <td>2000</td>
											</tr>
											<tr>
											   <td>2021/6/5</td>
											   <td>2500</td>
											</tr>
											<tr>
											   <td>2021/6/6</td>
											   <td>3000</td>
											</tr>
											<tr>
											   <td>2021/6/7</td>
											   <td>3500</td>
											</tr>
											<tr>
											   <td>2021/6/8</td>
											   <td>4000</td>
											</tr>
											<tr>
											   <td>2021/6/9</td>
											   <td>4500</td>
											</tr>
											<tr>
											   <td>2021/6/10</td>
											   <td>5000</td>
											</tr>
											<tr>
											   <td>2021/6/11</td>
											   <td>5500</td>
											</tr>
											<tr>
											   <td>2021/6/12</td>
											   <td>6000</td>
											</tr>
											<tr>
											   <td>2021/6/13</td>
											   <td>6500</td>
											</tr>
											<tr>
											   <td>2021/6/14</td>
											   <td>7000</td>
											</tr>
											<tr>
											   <td>2021/6/15</td>
											   <td>7500</td>
											</tr>
											<tr>
											   <td>2021/6/16</td>
											   <td>8000</td>
											</tr>
											<tr>
											   <td>2021/6/17</td>
											   <td>8500</td>
											</tr>
											<tr>
											   <td>2021/6/18</td>
											   <td>9000</td>
											</tr>
											<tr>
											   <td>2021/6/19</td>
											   <td>9500</td>
											</tr>
											<tr>
											   <td>2021/6/20</td>
											   <td>10000</td>
											</tr>
											<tr>
											   <td>2021/6/21</td>
											   <td>10500</td>
											</tr>
											<tr>
											   <td>2021/6/22</td>
											   <td>11000</td>
											</tr>
											<tr>
											   <td>2021/6/23</td>
											   <td>11500</td>
											</tr>
											<tr>
											   <td>2021/6/24</td>
											   <td>12000</td>
											</tr>
											<tr>
											   <td>2021/6/25</td>
											   <td>12500</td>
											</tr>
											<tr>
											   <td>2021/6/26</td>
											   <td>13000</td>
											</tr>
											<tr>
											   <td>2021/6/27</td>
											   <td>13500</td>
											</tr>
											<tr>
											   <td>2021/6/28</td>
											   <td>14000</td>
											</tr>
											<tr>
											   <td>2021/6/29</td>
											   <td>14500</td>
											</tr>
											<tr>
											   <td>2021/6/30</td>
											   <td>15000</td>
											</tr>
											<tr>
											   <td> </td>
											   <td> </td>
											</tr>
											<tr>
											   <td>2021/7/1</td>
											   <td>500</td>
											</tr>
											<tr>
											   <td>2021/7/2</td>
											   <td>1000</td>
											</tr>
											<tr>
											   <td>2021/7/3</td>
											   <td>1500</td>
											</tr>
											<tr>
											   <td>2021/7/4</td>
											   <td>2000</td>
											</tr>
											<tr>
											   <td>2021/7/5</td>
											   <td>2500</td>
											</tr>
											<tr>
											   <td>2021/7/6</td>
											   <td>3000</td>
											</tr>
											<tr>
											   <td>2021/7/7</td>
											   <td>3500</td>
											</tr>
											<tr>
											   <td>2021/7/8</td>
											   <td>4000</td>
											</tr>
											<tr>
											   <td>2021/7/9</td>
											   <td>4500</td>
											</tr>
											<tr>
											   <td>2021/7/10</td>
											   <td>5000</td>
											</tr>
											<tr>
											   <td>2021/7/11</td>
											   <td>5500</td>
											</tr>
											<tr>
											   <td>2021/7/12</td>
											   <td>6000</td>
											</tr>
											<tr>
											   <td>2021/7/13</td>
											   <td>6500</td>
											</tr>
											<tr>
											   <td>2021/7/14</td>
											   <td>7000</td>
											</tr>
											<tr>
											   <td>2021/7/15</td>
											   <td>7500</td>
											</tr>
											<tr>
											   <td>2021/7/16</td>
											   <td>8000</td>
											</tr>
											<tr>
											   <td>2021/7/17</td>
											   <td>8500</td>
											</tr>
											<tr>
											   <td>2021/7/18</td>
											   <td>9000</td>
											</tr>
											<tr>
											   <td>2021/7/19</td>
											   <td>9500</td>
											</tr>
											<tr>
											   <td>2021/7/20</td>
											   <td>10000</td>
											</tr>
											<tr>
											   <td>2021/7/21</td>
											   <td>10500</td>
											</tr>
											<tr>
											   <td>2021/7/22</td>
											   <td>11000</td>
											</tr>
											<tr>
											   <td>2021/7/23</td>
											   <td>11500</td>
											</tr>
											<tr>
											   <td>2021/7/24</td>
											   <td>12000</td>
											</tr>
											<tr>
											   <td>2021/7/25</td>
											   <td>12500</td>
											</tr>
											<tr>
											   <td>2021/7/26</td>
											   <td>13000</td>
											</tr>
											<tr>
											   <td>2021/7/27</td>
											   <td>13500</td>
											</tr>
											<tr>
											   <td>2021/7/28</td>
											   <td>14000</td>
											</tr>
											<tr>
											   <td>2021/7/29</td>
											   <td>14500</td>
											</tr>
											<tr>
											   <td>2021/7/30</td>
											   <td>15000</td>
											</tr>
											<tr>
											   <td>2021/7/31</td>
											   <td>15500</td>
											</tr>
											<tr>
											   <td>2021/8/1</td>
											   <td>500</td>
											</tr>
											<tr>
											   <td>2021/8/2</td>
											   <td>1000</td>
											</tr>
											<tr>
											   <td>2021/8/3</td>
											   <td>1500</td>
											</tr>
											<tr>
											   <td>2021/8/4</td>
											   <td>2000</td>
											</tr>
											<tr>
											   <td>2021/8/5</td>
											   <td>2500</td>
											</tr>
											<tr>
											   <td>2021/8/6</td>
											   <td>3000</td>
											</tr>
											<tr>
											   <td>2021/8/7</td>
											   <td>3500</td>
											</tr>
											<tr>
											   <td>2021/8/8</td>
											   <td>4000</td>
											</tr>
											<tr>
											   <td>2021/8/9</td>
											   <td>4500</td>
											</tr>
											<tr>
											   <td>2021/8/10</td>
											   <td>5000</td>
											</tr>
											<tr>
											   <td>2021/8/11</td>
											   <td>5500</td>
											</tr>
											<tr>
											   <td>2021/8/12</td>
											   <td>6000</td>
											</tr>
											<tr>
											   <td>2021/8/13</td>
											   <td>6500</td>
											</tr>
											<tr>
											   <td>2021/8/14</td>
											   <td>7000</td>
											</tr>
											<tr>
											   <td>2021/8/15</td>
											   <td>7500</td>
											</tr>
											<tr>
											   <td>2021/8/16</td>
											   <td>8000</td>
											</tr>
											<tr>
											   <td>2021/8/17</td>
											   <td>8500</td>
											</tr>
											<tr>
											   <td>2021/8/18</td>
											   <td>9000</td>
											</tr>
											<tr>
											   <td>2021/8/19</td>
											   <td>9500</td>
											</tr>
											<tr>
											   <td>2021/8/20</td>
											   <td>10000</td>
											</tr>
											<tr>
											   <td>2021/8/21</td>
											   <td>10500</td>
											</tr>
											<tr>
											   <td>2021/8/22</td>
											   <td>11000</td>
											</tr>
											<tr>
											   <td>2021/8/23</td>
											   <td>11500</td>
											</tr>
											<tr>
											   <td>2021/8/24</td>
											   <td>12000</td>
											</tr>
											<tr>
											   <td>2021/8/25</td>
											   <td>12500</td>
											</tr>
											<tr>
											   <td>2021/8/26</td>
											   <td>13000</td>
											</tr>
											<tr>
											   <td>2021/8/27</td>
											   <td>13500</td>
											</tr>
											<tr>
											   <td>2021/8/28</td>
											   <td>14000</td>
											</tr>
											<tr>
											   <td>2021/8/29</td>
											   <td>14500</td>
											</tr>
											<tr>
											   <td>2021/8/30</td>
											   <td>15000</td>
											</tr>
											<tr>
											   <td>2021/8/31</td>
											   <td>15500</td>
											</tr>
											<tr>
											   <td>2021/9/1</td>
											   <td>500</td>
											</tr>
											<tr>
											   <td>2021/9/2</td>
											   <td>1000</td>
											</tr>
											<tr>
											   <td>2021/9/3</td>
											   <td>1500</td>
											</tr>
											<tr>
											   <td>2021/9/4</td>
											   <td>2000</td>
											</tr>
											<tr>
											   <td>2021/9/5</td>
											   <td>2500</td>
											</tr>
											<tr>
											   <td>2021/9/6</td>
											   <td>3000</td>
											</tr>
											<tr>
											   <td>2021/9/7</td>
											   <td>3500</td>
											</tr>
											<tr>
											   <td>2021/9/8</td>
											   <td>4000</td>
											</tr>
											<tr>
											   <td>2021/9/9</td>
											   <td>4500</td>
											</tr>
											<tr>
											   <td>2021/9/10</td>
											   <td>5000</td>
											</tr>
											<tr>
											   <td>2021/9/11</td>
											   <td>5500</td>
											</tr>
											<tr>
											   <td>2021/9/12</td>
											   <td>6000</td>
											</tr>
											<tr>
											   <td>2021/9/13</td>
											   <td>6500</td>
											</tr>
											<tr>
											   <td>2021/9/14</td>
											   <td>7000</td>
											</tr>
											<tr>
											   <td>2021/9/15</td>
											   <td>7500</td>
											</tr>
											<tr>
											   <td>2021/9/16</td>
											   <td>8000</td>
											</tr>
											<tr>
											   <td>2021/9/17</td>
											   <td>8500</td>
											</tr>
											<tr>
											   <td>2021/9/18</td>
											   <td>9000</td>
											</tr>
											<tr>
											   <td>2021/9/19</td>
											   <td>9500</td>
											</tr>
											<tr>
											   <td>2021/9/20</td>
											   <td>10000</td>
											</tr>
											<tr>
											   <td>2021/9/21</td>
											   <td>10500</td>
											</tr>
											<tr>
											   <td>2021/9/22</td>
											   <td>11000</td>
											</tr>
											<tr>
											   <td>2021/9/23</td>
											   <td>11500</td>
											</tr>
											<tr>
											   <td>2021/9/24</td>
											   <td>12000</td>
											</tr>
											<tr>
											   <td>2021/9/25</td>
											   <td>12500</td>
											</tr>
											<tr>
											   <td>2021/9/26</td>
											   <td>13000</td>
											</tr>
											<tr>
											   <td>2021/9/27</td>
											   <td>13500</td>
											</tr>
											<tr>
											   <td>2021/9/28</td>
											   <td>14000</td>
											</tr>
											<tr>
											   <td>2021/9/29</td>
											   <td>14500</td>
											</tr>
											<tr>
											   <td>2021/9/30</td>
											   <td>15000</td>
											</tr>
											<tr>
											   <td></td>
											   <td> </td>
											</tr>
											<tr>
											   <td>2021/10/1</td>
											   <td>500</td>
											</tr>
											<tr>
											   <td>2021/10/2</td>
											   <td>1000</td>
											</tr>
											<tr>
											   <td>2021/10/3</td>
											   <td>1500</td>
											</tr>
											<tr>
											   <td>2021/10/4</td>
											   <td>2000</td>
											</tr>
											<tr>
											   <td>2021/10/5</td>
											   <td>2500</td>
											</tr>
											<tr>
											   <td>2021/10/6</td>
											   <td>3000</td>
											</tr>
											<tr>
											   <td>2021/10/7</td>
											   <td>3500</td>
											</tr>
											<tr>
											   <td>2021/10/8</td>
											   <td>4000</td>
											</tr>
											<tr>
											   <td>2021/10/9</td>
											   <td>4500</td>
											</tr>
											<tr>
											   <td>2021/10/10</td>
											   <td>5000</td>
											</tr>
											<tr>
											   <td>2021/10/11</td>
											   <td>5500</td>
											</tr>
											<tr>
											   <td>2021/10/12</td>
											   <td>6000</td>
											</tr>
											<tr>
											   <td>2021/10/13</td>
											   <td>6500</td>
											</tr>
											<tr>
											   <td>2021/10/14</td>
											   <td>7000</td>
											</tr>
											<tr>
											   <td>2021/10/15</td>
											   <td>7500</td>
											</tr>
											<tr>
											   <td>2021/10/16</td>
											   <td>8000</td>
											</tr>
											<tr>
											   <td>2021/10/17</td>
											   <td>8500</td>
											</tr>
											<tr>
											   <td>2021/10/18</td>
											   <td>9000</td>
											</tr>
											<tr>
											   <td>2021/10/19</td>
											   <td>9500</td>
											</tr>
											<tr>
											   <td>2021/10/20</td>
											   <td>10000</td>
											</tr>
											<tr>
											   <td>2021/10/21</td>
											   <td>10500</td>
											</tr>
											<tr>
											   <td>2021/10/22</td>
											   <td>11000</td>
											</tr>
											<tr>
											   <td>2021/10/23</td>
											   <td>11500</td>
											</tr>
											<tr>
											   <td>2021/10/24</td>
											   <td>12000</td>
											</tr>
											<tr>
											   <td>2021/10/25</td>
											   <td>12500</td>
											</tr>
											<tr>
											   <td>2021/10/26</td>
											   <td>13000</td>
											</tr>
											<tr>
											   <td>2021/10/27</td>
											   <td>13500</td>
											</tr>
											<tr>
											   <td>2021/10/28</td>
											   <td>14000</td>
											</tr>
											<tr>
											   <td>2021/10/29</td>
											   <td>14500</td>
											</tr>
											<tr>
											   <td>2021/10/30</td>
											   <td>15000</td>
											</tr>
											<tr>
											   <td>2021/10/31</td>
											   <td>15500</td>
											</tr>
											<tr>
											   <td>2021/11/1</td>
											   <td>500</td>
											</tr>
											<tr>
											   <td>2021/11/2</td>
											   <td>1000</td>
											</tr>
											<tr>
											   <td>2021/11/3</td>
											   <td>1500</td>
											</tr>
											<tr>
											   <td>2021/11/4</td>
											   <td>2000</td>
											</tr>
											<tr>
											   <td>2021/11/5</td>
											   <td>2500</td>
											</tr>
											<tr>
											   <td>2021/11/6</td>
											   <td>3000</td>
											</tr>
											<tr>
											   <td>2021/11/7</td>
											   <td>3500</td>
											</tr>
											<tr>
											   <td>2021/11/8</td>
											   <td>4000</td>
											</tr>
											<tr>
											   <td>2021/11/9</td>
											   <td>4500</td>
											</tr>
											<tr>
											   <td>2021/11/10</td>
											   <td>5000</td>
											</tr>
											<tr>
											   <td>2021/11/11</td>
											   <td>5500</td>
											</tr>
											<tr>
											   <td>2021/11/12</td>
											   <td>6000</td>
											</tr>
											<tr>
											   <td>2021/11/13</td>
											   <td>6500</td>
											</tr>
											<tr>
											   <td>2021/11/14</td>
											   <td>7000</td>
											</tr>
											<tr>
											   <td>2021/11/15</td>
											   <td>7500</td>
											</tr>
											<tr>
											   <td>2021/11/16</td>
											   <td>8000</td>
											</tr>
											<tr>
											   <td>2021/11/17</td>
											   <td>8500</td>
											</tr>
											<tr>
											   <td>2021/11/18</td>
											   <td>9000</td>
											</tr>
											<tr>
											   <td>2021/11/19</td>
											   <td>9500</td>
											</tr>
											<tr>
											   <td>2021/11/20</td>
											   <td>10000</td>
											</tr>
											<tr>
											   <td>2021/11/21</td>
											   <td>10500</td>
											</tr>
											<tr>
											   <td>2021/11/22</td>
											   <td>11000</td>
											</tr>
											<tr>
											   <td>2021/11/23</td>
											   <td>11500</td>
											</tr>
											<tr>
											   <td>2021/11/24</td>
											   <td>12000</td>
											</tr>
											<tr>
											   <td>2021/11/25</td>
											   <td>12500</td>
											</tr>
											<tr>
											   <td>2021/11/26</td>
											   <td>13000</td>
											</tr>
											<tr>
											   <td>2021/11/27</td>
											   <td>13500</td>
											</tr>
											<tr>
											   <td>2021/11/28</td>
											   <td>14000</td>
											</tr>
											<tr>
											   <td>2021/11/29</td>
											   <td>14500</td>
											</tr>
											<tr>
											   <td>2021/11/30</td>
											   <td>15000</td>
											</tr>
											<tr>
											   <td> </td>
											   <td> </td>
											</tr>
											<tr>
											   <td>2021/12/1</td>
											   <td>500</td>
											</tr>
											<tr>
											   <td>2021/12/2</td>
											   <td>1000</td>
											</tr>
											<tr>
											   <td>2021/12/3</td>
											   <td>1500</td>
											</tr>
											<tr>
											   <td>2021/12/4</td>
											   <td>2000</td>
											</tr>
											<tr>
											   <td>2021/12/5</td>
											   <td>2500</td>
											</tr>
											<tr>
											   <td>2021/12/6</td>
											   <td>3000</td>
											</tr>
											<tr>
											   <td>2021/12/7</td>
											   <td>3500</td>
											</tr>
											<tr>
											   <td>2021/12/8</td>
											   <td>4000</td>
											</tr>
											<tr>
											   <td>2021/12/9</td>
											   <td>4500</td>
											</tr>
											<tr>
											   <td>2021/12/10</td>
											   <td>5000</td>
											</tr>
											<tr>
											   <td>2021/12/11</td>
											   <td>5500</td>
											</tr>
											<tr>
											   <td>2021/12/12</td>
											   <td>6000</td>
											</tr>
											<tr>
											   <td>2021/12/13</td>
											   <td>6500</td>
											</tr>
											<tr>
											   <td>2021/12/14</td>
											   <td>7000</td>
											</tr>
											<tr>
											   <td>2021/12/15</td>
											   <td>7500</td>
											</tr>
											<tr>
											   <td>2021/12/16</td>
											   <td>8000</td>
											</tr>
											<tr>
											   <td>2021/12/17</td>
											   <td>8500</td>
											</tr>
											<tr>
											   <td>2021/12/18</td>
											   <td>9000</td>
											</tr>
											<tr>
											   <td>2021/12/19</td>
											   <td>9500</td>
											</tr>
											<tr>
											   <td>2021/12/20</td>
											   <td>10000</td>
											</tr>
											<tr>
											   <td>2021/12/21</td>
											   <td>10500</td>
											</tr>
											<tr>
											   <td>2021/12/22</td>
											   <td>11000</td>
											</tr>
											<tr>
											   <td>2021/12/23</td>
											   <td>11500</td>
											</tr>
											<tr>
											   <td>2021/12/24</td>
											   <td>12000</td>
											</tr>
											<tr>
											   <td>2021/12/25</td>
											   <td>12500</td>
											</tr>
											<tr>
											   <td>2021/12/26</td>
											   <td>13000</td>
											</tr>
											<tr>
											   <td>2021/12/27</td>
											   <td>13500</td>
											</tr>
											<tr>
											   <td>2021/12/28</td>
											   <td>14000</td>
											</tr>
											<tr>
											   <td>2021/12/29</td>
											   <td>14500</td>
											</tr>
											<tr>
											   <td>2021/12/30</td>
											   <td>15000</td>
											</tr>
											<tr>
											   <td>2021/12/31</td>
											   <td>15500</td>
											</tr>
                                            
                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        
                <!-- 최하단 footer -->
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; 사차원</div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        
        <!-- javascript 파일 import -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="../resources/js/admin/chart-area-demo.js"></script>
        <script src="../resources/js/admin/chart-bar-demo.js"></script>
        <script src="../resources/js/admin/chart-area-sell.js"></script>
        <script src="../resources/js/admin/chart-bar-sell.js"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        <script src="../resources/js/admin/datatables-coin.js"></script>
    </body>
</html>

